imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: false
    csrf_protection: false
    validation: { enable_annotations: true }
    serializer: false
    templating: false
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session: false
    fragments: false
    http_method_override: true
    assets: false
    php_errors:
        log: true

sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: false, auto_convert: false }
    view:        { annotations: false }
    cache:       { annotations: true }
    security:    { annotations: false }
    psr_message: { enabled: false }

enqueue:
    transport:
        default: 'amqp'
        amqp:
            host: '%rabbitmq_host'
            port: '%rabbitmq_port%'
            login: '%rabbitmq_login%'
            password: '%rabbitmq_password%'
            vhost: '%rabbitmq_vhost%'
    client:
        traceable_producer: false
        prefix: '%enqueue_prefix%'
        app_name: '%enqueue_app_name%'
        router_topic: '%enqueue_router_topic%'
        router_queue: '%enqueue_router_queue%'
        router_processor: 'enqueue.client.router_processor'
        default_processor_queue: 'default'
#        redelivered_delay_time: '%enqueue_redelivered_delay_time%'
